name: expire-action
description: Expire (delete) tags from your container registry
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  python_version:
    description: "version of python to run action with"
    required: false
    type: string
    default: "3.x"
  username:
    required: true
    type: string
    default: ""
  token:
    required: true
    type: string
    default: ""
  repo_type:
    required: false
    type: string
    default: "user"
  image_name:
    required: true
    type: string
    default: ""
  days_treshold:
    required: false
    type: int
    default: 30
  orgname:
    required: false
    type: string
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: "Setup Python ${{ inputs.python_version }}"
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
    
    - name: "Show Python Version"
      run: python --version
      shell: bash

    - name: "Install Python Dependencies"
      run: |
        python -m pip install --upgrade pip
        python -m pip install datetime json requests sys
      shell: bash
       
    - name: "Run tagexpire"
      run: "python tagexpire.py ${{ inputs.username }} ${{ inputs.token }} ${{ inputs.repo_type }} ${{ inputs.image_name }} ${{ inputs.days_treshold }} ${{ inputs.orgname }}" 
      shell: bash
